# @package _global_
agent: contextual_policy_iteration
agent_name: contextual_policy_iteration
agent_class: ContextualPolicyIteration
training_steps: 100
env_name: TiltedMarsRover
env_kwargs:
  transition_probabilities:
    - [0.5, 0.5]
    - [0.5, 0.5]
    - [0.5, 0.5]
    - [0.5, 0.5]
    - [0.5, 0.5]
context_schedule: round_robin
batch_size: 0
buffer_cls: SimpleBuffer
buffer_kwargs: {}
n_eval_episodes: 10

hydra:
  run:
    dir: "${outpath}/${agent_name}/${env_name}/${experiment_name}/seed_${seed}"
  sweep:
    dir: "${outpath}/${agent_name}/${env_name}/${experiment_name}/seed_${seed}"
