# configs/reinforce.yaml
hydra:
  run:
    dir: "${outpath}/${agent.name}/seed_${seed}/timestamp_${now:$Y-%m-%d_%H-%M-%S}"

# Gymnasium environment settings
env:
  name: LunarLander-v3
  kwargs:
    continuous: false
    gravity: -10.0
    enable_wind: false
    wind_power: 15.0
    turbulence_power: 1.5

# Random seed for reproducibility
seed: 0

# Agent hyperparameters
agent:
  name: REINFORCE
  lr: 1e-2
  gamma: 0.99
  hidden_size: 256
  hidden_layer_count: 2

# Training settings
train:
  episodes: 1000        # total episodes to train
  eval_interval: 50     # how often (in episodes) to run evaluation
  eval_episodes: 5      # number of episodes to evaluate

outpath: "results"